export const robots = [
    { id: 1, first_name: "User1", last_name: "Smith", email: "user1@example.com" },
    { id: 2, first_name: "User2", last_name: "Johnson", email: "user2@example.com" },
    { id: 3, first_name: "User3", last_name: "Williams", email: "user3@example.com" },
    { id: 4, first_name: "User4", last_name: "Brown", email: "user4@example.com" },
    { id: 5, first_name: "User5", last_name: "Jones", email: "user5@example.com" },
    { id: 6, first_name: "User6", last_name: "Garcia", email: "user6@example.com" },
    { id: 7, first_name: "User7", last_name: "Miller", email: "user7@example.com" },
    { id: 8, first_name: "User8", last_name: "Davis", email: "user8@example.com" },
    { id: 9, first_name: "User9", last_name: "Martinez", email: "user9@example.com" },
    { id: 10, first_name: "User10", last_name: "Hernandez", email: "user10@example.com" },
    { id: 11, first_name: "User11", last_name: "Lopez", email: "user11@example.com" },
    { id: 12, first_name: "User12", last_name: "Gonzalez", email: "user12@example.com" },
    { id: 13, first_name: "User13", last_name: "Wilson", email: "user13@example.com" },
    { id: 14, first_name: "User14", last_name: "Anderson", email: "user14@example.com" },
    { id: 15, first_name: "User15", last_name: "Thomas", email: "user15@example.com" },
    { id: 16, first_name: "User16", last_name: "Taylor", email: "user16@example.com" },
    { id: 17, first_name: "User17", last_name: "Moore", email: "user17@example.com" },
    { id: 18, first_name: "User18", last_name: "Jackson", email: "user18@example.com" },
    { id: 19, first_name: "User19", last_name: "Martin", email: "user19@example.com" },
    { id: 20, first_name: "User20", last_name: "Lee", email: "user20@example.com" }
];
